### ISSUE TITLE
Nilcord 1.12.2 java.lang.NoSuchMethodError: net.minecraft.entity.player.EntityPlayerMP.getDisplayName()

### ISSUE THREAD

**Issue by hobnob11** [unilock/nilcord#1]
hi, i've been using this mod with my 1.7.10 server and its been working great, I tried to add it to my 1.12.2 server and it crashes on startup: 

```
---- Minecraft Crash Report ----
// NormalASM deobfuscated this stacktrace using MCP's stable-39 mappings.
// Shall we play a game?

Time: 2024-08-19 06:43:45 UTC
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.entity.player.EntityPlayerMP.getDisplayName()Lnet/minecraft/util/text/ITextComponent;
    at cc.unilock.nilcord.util.TextUtils.parsePlayer(TextUtils.java:38)
    at cc.unilock.nilcord.EventListener.playerJoin(EventListener.java:48)
    at cc.unilock.nilcord.NilcordPremain$FMLEvents.onPlayerLoggedIn(NilcordPremain.java:57)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2549_FMLEvents_onPlayerLoggedIn_PlayerLoggedInEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:575)
    at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:219)
    at shadows.fastbench.net.HijackedDedicatedPlayerList.initializeConnectionToPlayer(HijackedDedicatedPlayerList.java:19)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:205)
    at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:285)
    at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:180)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:790)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:750)

(MixinBooter) Mixins in Stacktrace:
    net/minecraftforge/fml/common/eventhandler/EventBus:
        com.fuzs.aquaacrobatics.core.mixin.accessor.IEventBusAccessor (META-INF/mixins.aquaacrobatics.json) [unknown-location]
    net/minecraftforge/fml/common/FMLCommonHandler:
        mirror.normalasm.common.vanities.mixins.FMLCommonHandlerMixin (mixins.vanities.json) [unknown-location]
    net/minecraft/server/management/PlayerList:
        mod.acgaming.universaltweaks.bugfixes.entities.tracker.mixin.UTPlayerListMixin (mixins.bugfixes.entities.tracker.json) [unknown-location]
        mod.acgaming.universaltweaks.bugfixes.entities.dimensionchange.mixin.UTDimensionChangePlayerListMixin (mixins.bugfixes.entities.dimensionchange.json) [unknown-location]
        mod.acgaming.universaltweaks.bugfixes.entities.disconnectdupe.mixin.PlayerListInvoker (mixins.bugfixes.entities.disconnectdupe.json) [unknown-location]
    net/minecraft/server/MinecraftServer:
        mirror.normalasm.common.priorities.mixins.MinecraftServerMixin (mixins.priorities.json) [unknown-location]
    net/minecraft/server/dedicated/DedicatedServer:
        mod.acgaming.universaltweaks.tweaks.misc.buttons.snooper.mixin.UTSnooperServer (mixins.tweaks.misc.buttons.snooper.server.json) [unknown-location]
        mod.acgaming.universaltweaks.tweaks.misc.difficulty.mixin.UTDefaultDifficultyMPMixin (mixins.tweaks.misc.difficulty.server.json) [unknown-location]
    net/minecraft/server/MinecraftServer:
        mirror.normalasm.common.priorities.mixins.MinecraftServerMixin (mixins.priorities.json) [unknown-location]
```
[crash-2024-08-19_06.43.45-server.txt](https://github.com/user-attachments/files/16656759/crash-2024-08-19_06.43.45-server.txt)

**Comment by unilock** [comment]
Seems like the JAR I uploaded wasn't remapped? What the hell...?

**Comment by unilock** [comment]
Please test this version: https://modrinth.com/mod/nilcord/version/2.3.1+1.12.2+forge

**Comment by leepton** [comment]
Im having the same issue, even with the newest version posted above ^

The only difference in my case that it crashes on player joining

**Comment by unilock** [comment]
This version should ACTUALLY have this completely fixed: https://modrinth.com/mod/nilcord/version/2.3.3+1.12.2+forge
